---
galaxy_info:
  author: Vyacheslav Koksharov
  description: Brute-force protection with fail2ban (sshd jail enabled by default)
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - fail2ban
    - security

dependencies: []
