---
# STAGE environment - should mirror prod as closely as possible.
all:
  children:
    web:
      hosts:
        stage-web-01:
          ansible_host: 192.0.2.111
    db:
      hosts:
        stage-db-01:
          ansible_host: 192.0.2.121
