---
galaxy_info:
  author: Vyacheslav Koksharov
  description: Automatic security updates with unattended-upgrades
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - updates
    - security

dependencies: []
