---
# PROD environment.
all:
  children:
    web:
      hosts:
        prod-web-01:
          ansible_host: 198.51.100.11
        prod-web-02:
          ansible_host: 198.51.100.12
    db:
      hosts:
        prod-db-01:
          ansible_host: 198.51.100.21
