---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ common_apt_cache_valid_time }}"

- name: Upgrade installed packages
  ansible.builtin.apt:
    upgrade: safe
  when: common_upgrade_packages | bool

- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ common_packages + common_packages_extra }}"
    state: present

- name: Remove unwanted packages
  ansible.builtin.apt:
    name: "{{ common_packages_absent }}"
    state: absent
    purge: true
  when: common_packages_absent | length > 0
