---
- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
  notify: Restart cron

- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present
  when: common_ntp_enabled | bool

- name: Configure chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chrony
  when: common_ntp_enabled | bool

- name: Ensure chrony is running
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
  when: common_ntp_enabled | bool
